- name: Commit data.json
        run: |
          cp data.json public/data.json
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add public/data.json
          git commit -m "Update data.json" || echo "No changes"
          git push
